"""
tracer.py
---------
µLM Studio — FastAPI WebSocket tracing server

WebSocket protocol
------------------
Client → Server (JSON):
  {
    "code":        str,         # complete PyTorch nn.Module source
    "input_shape": list[int],   # optional, e.g. [2, 128, 512]
    "input_dtype": str          # optional: "float32" | "int64", default "float32"
  }

Server → Client (JSON, success):
  {
    "status":        "success",
    "graph":         { "nodes": [...], "edges": [...] },
    "model_name":    str,
    "trace_time_ms": float
  }

Server → Client (JSON, error):
  {
    "status": "error",
    "error": {
      "phase":     str,   # "parse" | "exec" | "trace" | "shape_prop" | "serialize"
      "type":      str,   # exception class name
      "message":   str,
      "traceback": str    # full traceback for PROBLEMS panel
    }
  }

REST endpoints
--------------
  GET  /health    → { "status": "ok", "torch_version": "..." }
  GET  /palette   → block palette metadata for frontend palette panel
  GET  /demo      → pre-computed static demo graph for VITE_DEMO_MODE
  POST /export    → downloadable clean .py file from graph + notebook code
"""

from __future__ import annotations

import asyncio
import datetime
import json
import os
import sys
import textwrap
import time
import traceback as tb
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import torch
import torch.nn as nn
import torch.fx as fx
from torch.fx.passes.shape_prop import ShapeProp

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel

from serializer import graph_to_json, build_mha_interior_view
from detect_mismatches import detect_mismatches, DEMO_MISMATCH_ATTENTION_FEEDFORWARD

# ─────────────────────────────────────────────────────────────────────────────
# App setup
# ─────────────────────────────────────────────────────────────────────────────

app = FastAPI(
    title="µLM Studio Tracer",
    description="torch.fx symbolic tracing backend for µLM Studio",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",   # Vite default
        "http://localhost:3000",   # CRA / alternate
        "http://127.0.0.1:5173",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Thread pool for running synchronous torch.fx tracing without blocking the
# asyncio event loop. Max 2 workers — tracing is CPU-bound, not I/O-bound.
_executor = ThreadPoolExecutor(max_workers=2, thread_name_prefix="mulm-tracer")

# Path to the pre-computed static demo graph (generated by serializer.py test)
_STATIC_DEMO_PATH = Path(__file__).parent / "static_demo_graph.json"

# ─────────────────────────────────────────────────────────────────────────────
# Palette metadata — the 10 blocks shipped in the prototype
# ─────────────────────────────────────────────────────────────────────────────

PALETTE_BLOCKS: List[Dict[str, Any]] = [
    # ── CORE ──────────────────────────────────────────────────────────────────
    {
        "id":             "Embedding",
        "label":          "Embedding",
        "pytorch_class":  "nn.Embedding",
        "category":       "CORE",
        "sync_state":     "traced",
        "default_params": {"num_embeddings": 50000, "embedding_dim": 512},
        "input_shape":    "[batch, seq]",
        "output_shape":   "[batch, seq, d_model]",
        "input_dtype":    "int64",
    },
    {
        "id":             "Linear",
        "label":          "Linear",
        "pytorch_class":  "nn.Linear",
        "category":       "CORE",
        "sync_state":     "traced",
        "default_params": {"in_features": 512, "out_features": 512},
        "input_shape":    "[*, in_features]",
        "output_shape":   "[*, out_features]",
        "input_dtype":    "float32",
    },
    {
        "id":             "FeedForward",
        "label":          "FeedForward",
        "pytorch_class":  "nn.Sequential(Linear, ReLU, Linear)",
        "category":       "CORE",
        "sync_state":     "traced",
        "default_params": {"d_model": 512, "dim_feedforward": 2048},
        "input_shape":    "[batch, seq, d_model]",
        "output_shape":   "[batch, seq, d_model]",
        "input_dtype":    "float32",
    },
    {
        "id":             "OutputHead",
        "label":          "Output Head",
        "pytorch_class":  "nn.Linear",
        "category":       "CORE",
        "sync_state":     "traced",
        "default_params": {"in_features": 512, "out_features": 50000},
        "input_shape":    "[*, d_model]",
        "output_shape":   "[*, vocab_size]",
        "input_dtype":    "float32",
    },
    # ── ATTENTION ─────────────────────────────────────────────────────────────
    {
        "id":             "MultiheadAttention",
        "label":          "Multi-Head Attention",
        "pytorch_class":  "nn.MultiheadAttention",
        "category":       "ATTENTION",
        "sync_state":     "atomic",          # ◆ badge — hardcoded contract
        "default_params": {"embed_dim": 512, "num_heads": 8, "batch_first": True},
        "input_shape":    "[batch, seq, d_model] × 3",
        "output_shape":   "[batch, seq, d_model]",
        "input_dtype":    "float32",
        "drill_down":     "mha_interior",    # frontend fetches /demo?view=mha_interior
    },
    # ── NORM ──────────────────────────────────────────────────────────────────
    {
        "id":             "LayerNorm",
        "label":          "LayerNorm",
        "pytorch_class":  "nn.LayerNorm",
        "category":       "NORM",
        "sync_state":     "traced",
        "default_params": {"normalized_shape": [512]},
        "input_shape":    "[*, d_model]",
        "output_shape":   "same shape",
        "input_dtype":    "float32",
    },
    {
        "id":             "RMSNorm",
        "label":          "RMSNorm",
        "pytorch_class":  "custom nn.Module",
        "category":       "NORM",
        "sync_state":     "traced",
        "default_params": {"d_model": 512},
        "input_shape":    "[*, d_model]",
        "output_shape":   "same shape",
        "input_dtype":    "float32",
    },
    # ── VISION ────────────────────────────────────────────────────────────────
    {
        "id":             "Conv2d",
        "label":          "Conv2D",
        "pytorch_class":  "nn.Conv2d",
        "category":       "VISION",
        "sync_state":     "traced",
        "default_params": {"in_channels": 3, "out_channels": 64, "kernel_size": 3, "padding": 1},
        "input_shape":    "[batch, C, H, W]",
        "output_shape":   "[batch, C_out, H_out, W_out]",
        "input_dtype":    "float32",
    },
    # ── REGULARIZATION ────────────────────────────────────────────────────────
    {
        "id":             "Dropout",
        "label":          "Dropout",
        "pytorch_class":  "nn.Dropout",
        "category":       "REGULARIZATION",
        "sync_state":     "traced",
        "default_params": {"p": 0.1},
        "input_shape":    "any",
        "output_shape":   "same shape",
        "input_dtype":    "float32",
    },
    # ── ACTIVATION ────────────────────────────────────────────────────────────
    {
        "id":             "Softmax",
        "label":          "Softmax",
        "pytorch_class":  "nn.Softmax",
        "category":       "ACTIVATION",
        "sync_state":     "traced",
        "default_params": {"dim": -1},
        "input_shape":    "[*, features]",
        "output_shape":   "same shape",
        "input_dtype":    "float32",
    },
]

# ─────────────────────────────────────────────────────────────────────────────
# Code execution sandbox
# ─────────────────────────────────────────────────────────────────────────────

# All classes defined by torch.nn, used to distinguish user-defined modules
# from torch built-ins when scanning the exec namespace.
_TORCH_NN_CLASSES: frozenset[type] = frozenset(
    obj for obj in vars(torch.nn).values()
    if isinstance(obj, type) and issubclass(obj, nn.Module)
)

# Modules blocked from import in the exec sandbox.
# This guards against accidental misuse (e.g. someone writes `import os; os.system(...)` )
# NOT designed to stop a determined adversary — this is a local single-user tool.
_BLOCKED_IMPORTS: frozenset[str] = frozenset([
    "os", "subprocess", "socket", "shutil", "pty",
    "signal", "ctypes", "cffi", "multiprocessing",
])


def _safe_import(name: str, *args: Any, **kwargs: Any) -> Any:
    """
    Replacement for __import__ in the exec sandbox.
    Blocks a small set of modules that have no business appearing in
    a PyTorch model definition (os, subprocess, socket, etc.).
    All torch/numpy/math imports pass through normally.
    """
    if name in _BLOCKED_IMPORTS:
        raise ImportError(
            f"Import '{name}' is not allowed in the µLM Studio sandbox. "
            "If you need this for your model, remove it from the cell first."
        )
    import builtins as _builtins
    return _builtins.__import__(name, *args, **kwargs)


def _build_exec_namespace() -> Dict[str, Any]:
    """
    Build the namespace for exec()'ing user PyTorch code.

    Provides the standard imports a PyTorch user expects at module level
    without needing to write them (though writing them is also fine — exec
    will just shadow our defaults).

    Important: always pass the builtins MODULE (not the __builtins__ name).
    In non-__main__ contexts (e.g. thread pool workers) __builtins__ is a
    dict that lacks __import__, silently breaking any import statement inside
    exec'd code. `import builtins` always gives the full module.
    """
    import builtins
    import torch.nn.functional as F
    import math

    return {
        "__builtins__": builtins,    # full module — guarantees __import__ is present
        "__import__":   _safe_import, # gated importer — blocks os/subprocess/socket
        "torch":  torch,
        "nn":     nn,
        "F":      F,
        "math":   math,
        "Tensor": torch.Tensor,
    }


def _find_model_class(
    namespace: Dict[str, Any],
    base_names: frozenset[str],
) -> Tuple[str, type]:
    """
    Scan the exec namespace for an nn.Module subclass defined by the user.

    Parameters
    ----------
    namespace   — the namespace dict after exec()
    base_names  — names that existed BEFORE exec (to identify new entries)

    Returns (class_name, class_object). Raises ValueError if none found.
    """
    candidates: List[Tuple[str, type]] = []

    for name, obj in namespace.items():
        if name in base_names:
            continue  # existed before exec — not user-defined
        if name.startswith("_"):
            continue
        if (
            isinstance(obj, type)
            and issubclass(obj, nn.Module)
            and obj not in _TORCH_NN_CLASSES
        ):
            candidates.append((name, obj))

    if not candidates:
        raise ValueError(
            "No nn.Module subclass found in the provided code. "
            "Define a class that inherits from nn.Module."
        )

    # If multiple candidates, return the last one — it's typically the
    # top-level class that composes the others (e.g., TransformerEncoderBlock
    # appears after its sub-modules in source order).
    return candidates[-1]


def _dtype_from_string(dtype_str: str) -> torch.dtype:
    """Map a dtype string from the WebSocket message to a torch.dtype."""
    _MAP = {
        "float32": torch.float32,
        "float":   torch.float32,
        "float16": torch.float16,
        "int64":   torch.int64,
        "long":    torch.int64,
        "int32":   torch.int32,
        "bool":    torch.bool,
    }
    return _MAP.get(dtype_str.lower(), torch.float32)


def _infer_dummy_input(
    model: nn.Module,
    requested_shape: Optional[List[int]],
    requested_dtype: Optional[str],
) -> torch.Tensor:
    """
    Produce a dummy input tensor suitable for ShapeProp on `model`.

    Priority:
      1. Use requested_shape + requested_dtype if provided by client.
      2. Detect model structure:
         - Contains nn.Embedding → int64 [2, 128]
         - Contains nn.Conv2d   → float32 [2, C_in, 32, 32]
         - Default              → float32 [2, 128, 512]  (transformer-style)

    Returns a zero/randn tensor on CPU.
    """
    import inspect

    dtype = _dtype_from_string(requested_dtype or "float32")

    if requested_shape:
        shape = requested_shape
        if dtype == torch.int64:
            return torch.zeros(shape, dtype=torch.int64)
        return torch.randn(shape, dtype=dtype)

    # ── Auto-detect from model structure ─────────────────────────────────────
    has_embedding = any(isinstance(m, nn.Embedding) for m in model.modules())
    conv2d_modules = [m for m in model.modules() if isinstance(m, nn.Conv2d)]

    if has_embedding and not conv2d_modules:
        # Sequence model with embedding (e.g. TissueLLMCell)
        return torch.zeros(2, 128, dtype=torch.int64)

    if conv2d_modules:
        # CNN: determine C_in from the first Conv2d
        first_conv = conv2d_modules[0]
        c_in = first_conv.in_channels
        return torch.randn(2, c_in, 32, 32)

    # ── Heuristic from forward() parameter name ───────────────────────────────
    try:
        sig = inspect.signature(model.forward)
        params = [p for p in sig.parameters if p != "self"]
        if params:
            first = params[0].lower()
            if any(kw in first for kw in ("token", "idx", "id", "index")):
                return torch.zeros(2, 128, dtype=torch.int64)
    except (ValueError, TypeError):
        pass

    # Default: 3-D transformer-style input
    return torch.randn(2, 128, 512)


# ─────────────────────────────────────────────────────────────────────────────
# Core tracing logic  (synchronous — runs in thread pool)
# ─────────────────────────────────────────────────────────────────────────────

def _do_trace(
    code: str,
    input_shape: Optional[List[int]],
    input_dtype: Optional[str],
) -> Dict[str, Any]:
    """
    Execute user code, trace the model, propagate shapes, and serialize.

    This function is synchronous and CPU-bound. It must be called via
    run_in_executor to avoid blocking the asyncio event loop.

    Returns a dict ready for JSON serialisation — either:
      {"status": "success", "graph": {...}, "model_name": ..., "trace_time_ms": ...}
    or
      {"status": "error", "error": {"phase": ..., "type": ..., "message": ..., "traceback": ...}}
    """
    t_start = time.perf_counter()

    # ── Phase 1: exec user code ───────────────────────────────────────────────
    namespace = _build_exec_namespace()
    base_names = frozenset(namespace.keys())

    try:
        exec(compile(code, "<mulm_user_code>", "exec"), namespace)  # noqa: S102
    except SyntaxError as exc:
        return _error_response(
            phase="parse",
            exc=exc,
            hint="Check for syntax errors in your model definition.",
        )
    except Exception as exc:
        return _error_response(
            phase="exec",
            exc=exc,
            hint="An error occurred while executing your model code.",
        )

    # ── Phase 2: locate and instantiate model class ───────────────────────────
    try:
        model_name, model_cls = _find_model_class(namespace, base_names)
        model = model_cls()
        model.eval()
    except Exception as exc:
        return _error_response(
            phase="exec",
            exc=exc,
            hint=(
                "Could not instantiate your model. "
                "Ensure the class has default values for all __init__ parameters."
            ),
        )

    # ── Phase 3: build dummy input ────────────────────────────────────────────
    try:
        dummy = _infer_dummy_input(model, input_shape, input_dtype)
    except Exception as exc:
        return _error_response(
            phase="exec",
            exc=exc,
            hint="Could not construct a dummy input tensor. Provide input_shape explicitly.",
        )

    # ── Phase 4: symbolic_trace ───────────────────────────────────────────────
    try:
        traced = fx.symbolic_trace(model)
    except Exception as exc:
        return _error_response(
            phase="trace",
            exc=exc,
            hint=(
                "torch.fx symbolic_trace failed. "
                "If your model contains data-dependent control flow or "
                "non-traceable operations, consider wrapping them."
            ),
        )

    # ── Phase 5: ShapeProp ────────────────────────────────────────────────────
    try:
        sp = ShapeProp(traced)
        sp.propagate(dummy)
    except Exception as exc:
        # ShapeProp failure is non-fatal: we can still serialize without shapes.
        # Log the error but continue — graph_to_json handles [unknown] gracefully.
        shape_error = _error_payload(phase="shape_prop", exc=exc)
    else:
        shape_error = None

    # ── Phase 6: serialize ────────────────────────────────────────────────────
    try:
        graph_json = graph_to_json(traced, model)
    except Exception as exc:
        return _error_response(
            phase="serialize",
            exc=exc,
            hint="Serialization failed. This is an internal error — please report it.",
        )

    t_ms = (time.perf_counter() - t_start) * 1000

    # ── Phase 7: mismatch detection ───────────────────────────────────────────
    # Run detect_mismatches on the serialized graph. Any failures here are
    # non-fatal — a detection bug must never prevent the graph from rendering.
    try:
        mismatches = detect_mismatches(graph_json)
    except Exception:
        mismatches = []

    # Stamp edges whose id appears in mismatches with status="mismatch"
    mismatch_edge_ids = {m["edge_id"] for m in mismatches}
    for edge in graph_json.get("edges", []):
        if edge.get("id") in mismatch_edge_ids:
            if edge.get("data") is None:
                edge["data"] = {}
            edge["data"]["status"] = "mismatch"

    result: Dict[str, Any] = {
        "status":        "success",
        "graph":         graph_json,
        "model_name":    model_name,
        "input_shape":   list(dummy.shape),
        "input_dtype":   str(dummy.dtype).replace("torch.", ""),
        "trace_time_ms": round(t_ms, 2),
        "mismatches":    mismatches,    # list of { edge_id, message, severity }
    }

    if shape_error:
        # Partial success: tracing worked but ShapeProp degraded
        result["warnings"] = [shape_error]

    return result


def _error_payload(
    phase: str,
    exc: Exception,
    hint: str = "",
) -> Dict[str, Any]:
    """Build the error dict that goes inside the 'error' key of the response."""
    full_tb = tb.format_exception(type(exc), exc, exc.__traceback__)
    return {
        "phase":     phase,
        "type":      type(exc).__name__,
        "message":   str(exc),
        "hint":      hint,
        "traceback": "".join(full_tb),
    }


def _error_response(
    phase: str,
    exc: Exception,
    hint: str = "",
) -> Dict[str, Any]:
    """Build the top-level error response dict."""
    return {
        "status": "error",
        "error":  _error_payload(phase=phase, exc=exc, hint=hint),
    }


# ─────────────────────────────────────────────────────────────────────────────
# WebSocket endpoint
# ─────────────────────────────────────────────────────────────────────────────

@app.websocket("/ws/trace")
async def ws_trace(websocket: WebSocket) -> None:
    """
    Real-time notebook → canvas tracing endpoint.

    The frontend connects once and sends messages with updated code on every
    debounced keystroke (300ms debounce in useTracer.js). The connection is
    kept alive for the duration of the session.

    On each message:
      1. Parse the JSON payload.
      2. Run tracing in the thread pool (non-blocking).
      3. Return the serialized graph or a structured error.
    """
    await websocket.accept()

    try:
        while True:
            raw = await websocket.receive_text()

            # ── Parse incoming message ────────────────────────────────────────
            try:
                msg: Dict[str, Any] = json.loads(raw)
            except json.JSONDecodeError as exc:
                await websocket.send_text(json.dumps({
                    "status": "error",
                    "error": {
                        "phase":   "parse",
                        "type":    "JSONDecodeError",
                        "message": f"Invalid JSON: {exc}",
                        "hint":    "The message must be a JSON object.",
                    },
                }))
                continue

            code        = msg.get("code", "")
            input_shape = msg.get("input_shape")   # list[int] or None
            input_dtype = msg.get("input_dtype")   # str or None

            if not code.strip():
                await websocket.send_text(json.dumps({
                    "status": "error",
                    "error": {
                        "phase":   "parse",
                        "type":    "ValueError",
                        "message": "Empty code received.",
                        "hint":    "Provide a PyTorch nn.Module class definition.",
                    },
                }))
                continue

            # ── Run tracing in thread pool (non-blocking) ─────────────────────
            loop = asyncio.get_event_loop()
            try:
                result = await asyncio.wait_for(
                    loop.run_in_executor(
                        _executor,
                        _do_trace,
                        code,
                        input_shape,
                        input_dtype,
                    ),
                    timeout=30.0,   # 30-second hard timeout per trace request
                )
            except asyncio.TimeoutError:
                result = {
                    "status": "error",
                    "error": {
                        "phase":   "trace",
                        "type":    "TimeoutError",
                        "message": "Tracing timed out after 30 seconds.",
                        "hint":    "Your model may contain an infinite loop or be too large.",
                    },
                }

            await websocket.send_text(json.dumps(result))

    except WebSocketDisconnect:
        pass   # Client disconnected — normal, nothing to log
    except Exception as exc:
        # Catch-all: something unexpected happened (OOM, driver crash, etc.).
        # Try to send a final error frame before the connection closes.
        # We do NOT re-raise — uvicorn will close the socket gracefully.
        try:
            await websocket.send_text(json.dumps({
                "status": "error",
                "error": {
                    "phase":   "server",
                    "type":    type(exc).__name__,
                    "message": str(exc),
                    "hint":    "An unexpected server error occurred. Reconnect to continue.",
                    "traceback": tb.format_exc(),
                },
            }))
        except Exception:
            pass  # socket already dead — nothing we can do


# ─────────────────────────────────────────────────────────────────────────────
# REST endpoints
# ─────────────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health() -> JSONResponse:
    """Health check. Also confirms the PyTorch environment is loaded."""
    return JSONResponse({
        "status":         "ok",
        "torch_version":  torch.__version__,
        "cuda_available": torch.cuda.is_available(),
        "python_version": sys.version.split()[0],
    })


@app.get("/palette")
async def palette() -> JSONResponse:
    """
    Block palette metadata.
    The frontend uses this to populate the left palette panel.
    Grouped by category in the order defined in PALETTE_BLOCKS.
    """
    grouped: Dict[str, List[Dict]] = {}
    for block in PALETTE_BLOCKS:
        cat = block["category"]
        grouped.setdefault(cat, []).append(block)

    return JSONResponse({
        "categories": list(grouped.keys()),
        "blocks_by_category": grouped,
        "blocks": PALETTE_BLOCKS,
    })


@app.get("/demo")
async def demo(view: str = "transformer") -> JSONResponse:
    """
    Pre-computed static demo graph for VITE_DEMO_MODE=true.

    Query params:
      ?view=transformer      — full TransformerEncoderBlock graph (default)
      ?view=mha_interior     — MHA drill-down interior view

    The static_demo_graph.json is generated by running:
        python serializer.py   (which also saves static_demo_graph.json)
    If the file doesn't exist, this endpoint returns a live-computed result.
    """
    if view == "mha_interior":
        return JSONResponse(build_mha_interior_view(embed_dim=512, num_heads=8))

    if _STATIC_DEMO_PATH.exists():
        with open(_STATIC_DEMO_PATH, encoding="utf-8") as f:
            static = json.load(f)
        # static_demo_graph.json has key "transformer" (saved by serializer.py test)
        graph = static.get("transformer") or static
        return JSONResponse(graph)

    # Fallback: compute live if file not found
    _TRANSFORMER_CODE = """
import torch
import torch.nn as nn

class TransformerEncoderBlock(nn.Module):
    def __init__(self, d_model=512, nhead=8, dim_feedforward=2048, dropout=0.1):
        super().__init__()
        self.attention   = nn.MultiheadAttention(d_model, nhead, dropout=dropout, batch_first=True)
        self.norm1       = nn.LayerNorm(d_model)
        self.norm2       = nn.LayerNorm(d_model)
        self.feedforward = nn.Sequential(
            nn.Linear(d_model, dim_feedforward),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(dim_feedforward, d_model),
        )
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        attn_out, _ = self.attention(x, x, x)
        x = self.norm1(x + self.dropout(attn_out))
        ff_out = self.feedforward(x)
        x = self.norm2(x + self.dropout(ff_out))
        return x
"""
    loop = asyncio.get_event_loop()
    result = await loop.run_in_executor(
        _executor, _do_trace, _TRANSFORMER_CODE, [2, 128, 512], "float32"
    )
    if result["status"] == "success":
        return JSONResponse(result["graph"])
    return JSONResponse(result, status_code=500)


# ─────────────────────────────────────────────────────────────────────────────
# Export endpoint
# ─────────────────────────────────────────────────────────────────────────────

class ExportRequest(BaseModel):
    """
    Request body for POST /export.

    code       — the full notebook code string (what the user typed)
    graph      — the last successful graph_to_json() output (for metadata)
    model_name — optional override; inferred from graph nodes if omitted
    """
    code:       str
    graph:      Dict[str, Any]
    model_name: Optional[str] = None


def _generate_export_code(
    notebook_code: str,
    graph: Dict[str, Any],
    model_name: str,
) -> str:
    """
    Produce a clean, standalone .py file from the notebook code + graph metadata.

    Output layout
    -------------
    1. µLM Studio header comment (architecture, date, shape summary)
    2. Deduplicated import block (torch + nn always guaranteed)
    3. The model class source (from notebook_code, stripped of stray lines)
    4. A runnable __main__ block with a forward-pass smoke test

    The function is defensive: if any inspection step fails it falls back
    to the raw notebook code with just the header prepended.
    """
    # ── Collect shape metadata from graph for the header ─────────────────────
    nodes = graph.get("nodes", [])
    input_node  = next((n for n in nodes if n.get("type") == "mlmInputNode"),  None)
    output_node = next((n for n in nodes if n.get("type") == "mlmOutputNode"), None)
    input_shape  = input_node["data"]["shape"]  if input_node  else "unknown"
    output_shape = output_node["data"]["shape"] if output_node else "unknown"

    # Count by category for the architecture summary line
    categories: Dict[str, int] = {}
    for n in nodes:
        cat = n.get("data", {}).get("category", "CORE")
        categories[cat] = categories.get(cat, 0) + 1
    arch_summary = ", ".join(f"{v}× {k}" for k, v in sorted(categories.items()) if k not in ("INPUT", "OUTPUT"))

    # ── Build the __main__ smoke test ─────────────────────────────────────────
    # Infer a concrete dummy tensor from the input_shape string, e.g. "[2, 128, 512]"
    try:
        # Parse the shape string e.g. "[2, 128, 512]" → [2, 128, 512]
        raw = input_shape.strip("[]").split(",")
        dims = [int(d.strip()) for d in raw if d.strip().lstrip("-").isdigit()]
        if dims:
            dtype_node = input_node["data"].get("params", {}).get("dtype", "")
            if "int" in dtype_node.lower():
                dummy_call = f"torch.zeros({dims}, dtype=torch.long)"
            else:
                dummy_call = f"torch.randn({dims})"
        else:
            dummy_call = "torch.randn(2, 128, 512)  # adjust shape for your model"
    except Exception:
        dummy_call = "torch.randn(2, 128, 512)  # adjust shape for your model"

    main_block = textwrap.dedent(f"""
        if __name__ == "__main__":
            model = {model_name}()
            model.eval()
            x = {dummy_call}
            with torch.no_grad():
                out = model(x)
            print(f"Input  shape : {{x.shape}}")
            print(f"Output shape : {{out.shape}}")
            print(f"Parameters   : {{sum(p.numel() for p in model.parameters()):,}}")
    """).rstrip()

    # ── Ensure import block ───────────────────────────────────────────────────
    has_torch_import = "import torch" in notebook_code
    has_nn_import    = "import torch.nn" in notebook_code or "from torch import nn" in notebook_code

    import_lines: List[str] = []
    if not has_torch_import:
        import_lines.append("import torch")
    if not has_nn_import:
        import_lines.append("import torch.nn as nn")
    import_block = ("\n".join(import_lines) + "\n\n") if import_lines else ""

    # ── Strip the notebook code of any trailing whitespace/blank lines ────────
    clean_code = notebook_code.rstrip()

    # ── Assemble the final file ───────────────────────────────────────────────
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    header = textwrap.dedent(f"""\
        # =============================================================================
        # Generated by µLM Studio
        # Architecture : {model_name}
        # Summary      : {arch_summary}
        # Input shape  : {input_shape}
        # Output shape : {output_shape}
        # Exported     : {now}
        # =============================================================================
    """)

    return "\n".join(filter(None, [
        header,
        import_block,
        clean_code,
        "",
        main_block,
        "",  # trailing newline
    ]))

# ─────────────────────────────────────────────────────────────────────────────
# Mismatch detection endpoint
# ─────────────────────────────────────────────────────────────────────────────

class MismatchRequest(BaseModel):
    """
    Request body for POST /mismatches.
    graph — the current graph_to_json() output (nodes + edges).
    """
    graph: Dict[str, Any]


@app.post("/mismatches")
async def check_mismatches(req: MismatchRequest) -> JSONResponse:
    """
    Run shape-mismatch detection on an arbitrary graph JSON.

    Accepts the same graph schema emitted by the WebSocket /ws/trace endpoint.
    Returns:
      { "mismatches": [ { edge_id, source_id, target_id, message, severity } ] }

    The WebSocket endpoint already includes mismatches inline in every success
    response. This REST endpoint exists for:
      - Testing / debugging during development
      - VITE_DEMO_MODE (frontend fetches /demo then calls /mismatches to annotate)
      - Future: re-running detection after the user edits the graph on the canvas
    """
    try:
        results = detect_mismatches(req.graph)
    except Exception as exc:
        return JSONResponse(
            {"error": str(exc), "mismatches": []},
            status_code=500,
        )
    return JSONResponse({"mismatches": results})


@app.post("/export")
async def export_model(req: ExportRequest) -> Response:
    """
    Generate a downloadable standalone .py file from the current canvas state.

    The exported file is a clean, self-contained Python script that:
      - Defines the model class exactly as typed in the notebook
      - Includes a __main__ block with a forward-pass smoke test
      - Has a µLM Studio header comment with shape + architecture metadata

    Request body: { "code": str, "graph": {...}, "model_name": str | null }
    Response:     text/plain with Content-Disposition: attachment
    """
    # Determine model name: prefer explicit, else scan graph nodes
    model_name = req.model_name
    if not model_name:
        # Try to read it from the graph — the canvas always has the last good name
        nodes = req.graph.get("nodes", [])
        # Use the first call_module node's label as the architecture name
        module_node = next(
            (n for n in nodes if n.get("data", {}).get("op") == "call_module"),
            None,
        )
        model_name = module_node["data"].get("label", "Model") if module_node else "Model"

    try:
        py_source = _generate_export_code(
            notebook_code=req.code,
            graph=req.graph,
            model_name=model_name,
        )
    except Exception as exc:
        # Export generation failed — return the raw code with a minimal header
        # so the user is never left with nothing to download.
        now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
        py_source = (
            f"# Generated by µLM Studio — {now}\n"
            f"# Note: automatic header generation failed ({type(exc).__name__}: {exc})\n\n"
            + req.code
        )

    safe_name = model_name.replace(" ", "_").replace("/", "_") or "model"
    filename  = f"{safe_name}.py"

    return Response(
        content=py_source,
        media_type="text/plain; charset=utf-8",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


# ─────────────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn

    print("µLM Studio — Tracer Backend")
    print(f"PyTorch  : {torch.__version__}")
    print(f"CUDA     : {torch.cuda.is_available()}")
    print(f"Endpoints:")
    print("  WS   ws://localhost:8000/ws/trace")
    print("  GET  http://localhost:8000/health")
    print("  GET  http://localhost:8000/palette")
    print("  GET  http://localhost:8000/demo")
    print("  GET  http://localhost:8000/demo?view=mha_interior")
    print("  POST http://localhost:8000/export")
    print()

    uvicorn.run(
        "tracer:app",
        host="0.0.0.0",
        port=8000,
        reload=False,      # disable reload — it doesn't play well with torch
        log_level="info",
    )
